### ISSUE TITLE
Cannot specify location name in geocoding.dart api

### ISSUE THREAD

**Issue by tarragona2007** [Neurs12/open-meteo-dart#1]
typo in geocoding.dart class line 21 : String args = (createNullableParam("name", name) instead of String args = (createNullableParam(name, "name")

**Comment by Neurs12** [comment]
Whoops, thanks for noticing. Fixed in a83ea96. Pushed this change on version 1.0.6.

**Comment by kemolumi** [comment]
Whoops, thanks for noticing. Fixed in a83ea96. Pushed this change on version 1.0.6.
